# This file is part of aptscan
# https://github.com/scorphus/aptscan

# Licensed under the BSD-3-Clause license:
# https://opensource.org/licenses/BSD-3-Clause
# Copyright (c) 2024, Pablo S. Blum de Aguiar <scorphus@gmail.com>

[tool.black]
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | dist
  )/
)
'''
line-length = 99

[tool.mypy]
exclude = [
    "^tests/test_.*\\.py$",
    "^setup\\.py$",
]
